"""Add document_url to stock_transactions

Revision ID: 0a3b11d65bc6
Revises: 4b2424e22bac
Create Date: 2026-08-20 11:41:06.521838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3b11d65bc6'
down_revision: Union[str, None] = '4b2424e22bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transactions', sa.Column('document_url', sa.String(length=500), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_transactions', 'document_url', schema='solar')
    # ### end Alembic commands ###
