"""add employee_daily_expense

Revision ID: 12ae031159a1
Revises: 4ef5b471629f
Create Date: 2026-08-29 12:37:01.948640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ae031159a1'
down_revision: Union[str, None] = '4ef5b471629f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_daily_expenses',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_employee_daily_expenses_employee_id'), 'employee_daily_expenses', ['employee_id'], unique=False, schema='solar')
    op.create_index(op.f('ix_solar_employee_daily_expenses_expense_date'), 'employee_daily_expenses', ['expense_date'], unique=False, schema='solar')
    op.drop_column('employee_financials', 'expenses', schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_financials', sa.Column('expenses', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False), schema='solar')
    op.drop_index(op.f('ix_solar_employee_daily_expenses_expense_date'), table_name='employee_daily_expenses', schema='solar')
    op.drop_index(op.f('ix_solar_employee_daily_expenses_employee_id'), table_name='employee_daily_expenses', schema='solar')
    op.drop_table('employee_daily_expenses', schema='solar')
    # ### end Alembic commands ###
