"""Add tool photos and submission tracking

Revision ID: 1b0bf049cedc
Revises: 1eab7937453e
Create Date: 2026-08-21 22:19:16.215482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0bf049cedc'
down_revision: Union[str, None] = '1eab7937453e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('tool_photo_before', sa.Text(), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('tool_photo_after', sa.Text(), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'submitted_at', schema='solar')
    op.drop_column('site_visits', 'tool_photo_after', schema='solar')
    op.drop_column('site_visits', 'tool_photo_before', schema='solar')
    # ### end Alembic commands ###
