"""add proof_url to employee_daily_expenses

Revision ID: 1dbf8f65d4e0
Revises: 94a4fba9f5d4
Create Date: 2026-09-08 11:32:08.879924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbf8f65d4e0'
down_revision: Union[str, None] = '94a4fba9f5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_daily_expenses', sa.Column('proof_url', sa.String(length=500), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_daily_expenses', 'proof_url', schema='solar')
    # ### end Alembic commands ###
