"""Add project and stages to site visits

Revision ID: 1eab7937453e
Revises: 6ecb8f5330e2
Create Date: 2026-08-21 16:31:20.984309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eab7937453e'
down_revision: Union[str, None] = '6ecb8f5330e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'payments', 'projects', ['project_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='CASCADE')
    op.add_column('site_visit_photos', sa.Column('stage', sa.String(length=100), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('project_id', sa.String(length=36), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('system_type', sa.String(length=100), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('completed_stages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='solar')
    op.alter_column('site_visits', 'lead_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               schema='solar')

    op.create_foreign_key(None, 'site_visits', 'projects', ['project_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_visits', schema='solar', type_='foreignkey')

    op.alter_column('site_visits', 'lead_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               schema='solar')
    op.drop_column('site_visits', 'completed_stages', schema='solar')
    op.drop_column('site_visits', 'system_type', schema='solar')
    op.drop_column('site_visits', 'project_id', schema='solar')
    op.drop_column('site_visit_photos', 'stage', schema='solar')
    op.drop_constraint(None, 'payments', schema='solar', type_='foreignkey')
    # ### end Alembic commands ###
