"""add eb applications

Revision ID: 3f475a42e7ac
Revises: 1b0bf049cedc
Create Date: 2026-08-23 19:34:09.510753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f475a42e7ac'
down_revision: Union[str, None] = '1b0bf049cedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eb_applications',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_team', sa.String(length=100), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_employee_id', sa.String(length=36), nullable=True),
    sa.Column('current_stage', sa.Enum('Application Received', 'EB Document Verification', 'Application Submitted in Portal - Admin', 'Handover Application with EB Meter Supply', name='eb_app_stage_enum', schema='solar'), nullable=False),
    sa.Column('verification_status', sa.Enum('Pending', 'VERIFIED', 'NOT_VERIFIED', name='eb_verification_status_enum', schema='solar'), nullable=False),
    sa.Column('verification_reason', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('portal_submission_status', sa.Enum('Pending', 'COMPLETED', name='eb_portal_status_enum', schema='solar'), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=36), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('portal_reference', sa.String(length=200), nullable=True),
    sa.Column('portal_remarks', sa.Text(), nullable=True),
    sa.Column('handover_status', sa.Enum('Pending', 'COMPLETED', name='eb_handover_status_enum', schema='solar'), nullable=False),
    sa.Column('handed_over_by_id', sa.String(length=36), nullable=True),
    sa.Column('handover_date', sa.DateTime(), nullable=True),
    sa.Column('meter_supply_details', sa.Text(), nullable=True),
    sa.Column('handover_remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handed_over_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id'),
    schema='solar'
    )
    op.create_table('eb_stage_histories',
    sa.Column('eb_application_id', sa.String(length=36), nullable=False),
    sa.Column('from_stage', sa.String(length=100), nullable=True),
    sa.Column('to_stage', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eb_application_id'], ['solar.eb_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_eb_stage_histories_eb_application_id'), 'eb_stage_histories', ['eb_application_id'], unique=False, schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_eb_stage_histories_eb_application_id'), table_name='eb_stage_histories', schema='solar')
    op.drop_table('eb_stage_histories', schema='solar')
    op.drop_table('eb_applications', schema='solar')
    # ### end Alembic commands ###
