"""Add site visit details

Revision ID: 412ff2f4f4e3
Revises: b5920c4fcbf1
Create Date: 2026-08-28 13:24:03.197034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '412ff2f4f4e3'
down_revision: Union[str, None] = 'b5920c4fcbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('installation_area', sa.String(length=500), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('measurements', sa.String(length=500), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('roof_ground_details', sa.String(length=500), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('raw_materials', sa.Text(), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('raw_material_details', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='solar')
    op.add_column('site_visits', sa.Column('cable_accessories', sa.String(length=500), nullable=True), schema='solar')
    op.add_column('site_visits', sa.Column('stock_availability_status', sa.String(length=100), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'stock_availability_status', schema='solar')
    op.drop_column('site_visits', 'cable_accessories', schema='solar')
    op.drop_column('site_visits', 'raw_material_details', schema='solar')
    op.drop_column('site_visits', 'raw_materials', schema='solar')
    op.drop_column('site_visits', 'roof_ground_details', schema='solar')
    op.drop_column('site_visits', 'measurements', schema='solar')
    op.drop_column('site_visits', 'installation_area', schema='solar')
    # ### end Alembic commands ###
