"""Add attendance_records

Revision ID: 4b2424e22bac
Revises: 7071096f0bf6
Create Date: 2026-08-19 17:59:29.325550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2424e22bac'
down_revision: Union[str, None] = '7071096f0bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('check_in_time', sa.String(length=20), nullable=True),
    sa.Column('check_out_time', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('Present', 'Absent', 'On Leave', name='attendance_status_enum', schema='solar'), nullable=False),
    sa.Column('type', sa.Enum('Office', 'Field', name='attendance_type_enum', schema='solar'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False, schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_attendance_records_employee_id'), table_name='attendance_records', schema='solar')
    op.drop_table('attendance_records', schema='solar')
    # ### end Alembic commands ###
