"""Add financial_month to employee_financials

Revision ID: 4ef5b471629f
Revises: f6e461f7144e
Create Date: 2026-08-29 12:15:58.153736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef5b471629f'
down_revision: Union[str, None] = 'f6e461f7144e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_financials', sa.Column('financial_month', sa.String(length=7), nullable=False, server_default='2026-08'), schema='solar')
    op.drop_constraint('uq_employee_financial', 'employee_financials', schema='solar', type_='unique')
    op.drop_index('ix_solar_employee_financials_employee_id', table_name='employee_financials', schema='solar')
    op.create_index(op.f('ix_solar_employee_financials_employee_id'), 'employee_financials', ['employee_id'], unique=False, schema='solar')
    op.create_index(op.f('ix_solar_employee_financials_financial_month'), 'employee_financials', ['financial_month'], unique=False, schema='solar')
    op.create_unique_constraint('uq_emp_financial_month', 'employee_financials', ['employee_id', 'financial_month'], schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emp_financial_month', 'employee_financials', schema='solar', type_='unique')
    op.drop_index(op.f('ix_solar_employee_financials_financial_month'), table_name='employee_financials', schema='solar')
    op.drop_index(op.f('ix_solar_employee_financials_employee_id'), table_name='employee_financials', schema='solar')
    op.create_index('ix_solar_employee_financials_employee_id', 'employee_financials', ['employee_id'], unique=True, schema='solar')
    op.create_unique_constraint('uq_employee_financial', 'employee_financials', ['employee_id'], schema='solar')
    op.drop_column('employee_financials', 'financial_month', schema='solar')
    # ### end Alembic commands ###
