"""Add missing fields to invoices

Revision ID: 542149f0175e
Revises: 9c4152e335a7
Create Date: 2026-08-21 12:54:03.897453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542149f0175e'
down_revision: Union[str, None] = '9c4152e335a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('quotation_number', sa.String(length=50), nullable=True), schema='solar')
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=200), nullable=True), schema='solar')
    op.add_column('invoices', sa.Column('site', sa.String(length=200), nullable=True), schema='solar')
    op.add_column('invoices', sa.Column('project_type', sa.String(length=100), nullable=True), schema='solar')
    op.add_column('invoices', sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=False), schema='solar')
    op.add_column('invoices', sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'balance_amount', schema='solar')
    op.drop_column('invoices', 'advance_amount', schema='solar')
    op.drop_column('invoices', 'project_type', schema='solar')
    op.drop_column('invoices', 'site', schema='solar')
    op.drop_column('invoices', 'customer_name', schema='solar')
    op.drop_column('invoices', 'quotation_number', schema='solar')
    # ### end Alembic commands ###
