"""Add EmployeeRevenue

Revision ID: 6ecb8f5330e2
Revises: 542149f0175e
Create Date: 2026-08-21 15:40:47.846717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecb8f5330e2'
down_revision: Union[str, None] = '542149f0175e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_revenues',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_date', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['solar.invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'employee_id', name='uq_invoice_employee'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_employee_revenues_employee_id'), 'employee_revenues', ['employee_id'], unique=False, schema='solar')
    op.create_index(op.f('ix_solar_employee_revenues_invoice_id'), 'employee_revenues', ['invoice_id'], unique=False, schema='solar')
    op.create_index(op.f('ix_solar_employee_revenues_project_id'), 'employee_revenues', ['project_id'], unique=False, schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_employee_revenues_project_id'), table_name='employee_revenues', schema='solar')
    op.drop_index(op.f('ix_solar_employee_revenues_invoice_id'), table_name='employee_revenues', schema='solar')
    op.drop_index(op.f('ix_solar_employee_revenues_employee_id'), table_name='employee_revenues', schema='solar')
    op.drop_table('employee_revenues', schema='solar')
    # ### end Alembic commands ###
