"""Make project_id nullable in employee revenue

Revision ID: 848e2349edf5
Revises: 90509fdfc544
Create Date: 2026-08-31 13:00:47.305212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848e2349edf5'
down_revision: Union[str, None] = '90509fdfc544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_revenues', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_revenues', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               schema='solar')
    # ### end Alembic commands ###
