"""add eb_number to quotations

Revision ID: 8831bd19dd8a
Revises: a6898c7b2c05
Create Date: 2026-08-27 12:12:47.629715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8831bd19dd8a'
down_revision: Union[str, None] = 'a6898c7b2c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('eb_number', sa.String(length=100), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'eb_number', schema='solar')
    # ### end Alembic commands ###
