"""Update employee revenue for quotation attribution

Revision ID: 90509fdfc544
Revises: 9f0acd30f7a0
Create Date: 2026-08-31 12:59:41.949809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90509fdfc544'
down_revision: Union[str, None] = '9f0acd30f7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_revenues', sa.Column('quotation_id', sa.String(length=36), nullable=True), schema='solar')
    op.add_column('employee_revenues', sa.Column('revenue_date', sa.String(length=20), nullable=True), schema='solar')
    
    # Backfill revenue_date for existing rows using invoice_date or created_at
    op.execute(
        "UPDATE solar.employee_revenues "
        "SET revenue_date = COALESCE(invoice_date, TO_CHAR(created_at, 'YYYY-MM-DD'), '') "
        "WHERE revenue_date IS NULL"
    )
    
    op.alter_column('employee_revenues', 'revenue_date',
               existing_type=sa.String(length=20),
               nullable=False,
               schema='solar')
    op.alter_column('employee_revenues', 'invoice_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               schema='solar')
    op.alter_column('employee_revenues', 'invoice_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               schema='solar')
    op.drop_constraint('uq_invoice_employee', 'employee_revenues', schema='solar', type_='unique')
    op.create_index(op.f('ix_solar_employee_revenues_quotation_id'), 'employee_revenues', ['quotation_id'], unique=False, schema='solar')
    op.create_unique_constraint('uq_quotation_employee', 'employee_revenues', ['quotation_id', 'employee_id'], schema='solar')
    op.create_foreign_key(None, 'employee_revenues', 'quotations', ['quotation_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_revenues', schema='solar', type_='foreignkey')
    op.drop_constraint('uq_quotation_employee', 'employee_revenues', schema='solar', type_='unique')
    op.drop_index(op.f('ix_solar_employee_revenues_quotation_id'), table_name='employee_revenues', schema='solar')
    op.create_unique_constraint('uq_invoice_employee', 'employee_revenues', ['invoice_id', 'employee_id'], schema='solar')
    op.alter_column('employee_revenues', 'invoice_date',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               schema='solar')
    op.alter_column('employee_revenues', 'invoice_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               schema='solar')
    op.drop_column('employee_revenues', 'revenue_date', schema='solar')
    op.drop_column('employee_revenues', 'quotation_id', schema='solar')
    # ### end Alembic commands ###
