"""Add Invoice and GSTPeriod models

Revision ID: 9c4152e335a7
Revises: 0a3b11d65bc6
Create Date: 2026-08-21 12:03:02.590762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c4152e335a7'
down_revision: Union[str, None] = '0a3b11d65bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gst_periods',
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_payable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('invoice_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('initial_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('weekend_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_gst_periods_period_month'), 'gst_periods', ['period_month'], unique=True, schema='solar')
    op.create_table('invoices',
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('issue_date', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Generated', 'Cancelled', name='invoice_status_enum', schema='solar'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['solar.quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True, schema='solar')
    op.alter_column('payments', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               schema='solar')
    op.drop_index(op.f('ix_solar_invoices_invoice_number'), table_name='invoices', schema='solar')
    op.drop_table('invoices', schema='solar')
    op.drop_index(op.f('ix_solar_gst_periods_period_month'), table_name='gst_periods', schema='solar')
    op.drop_table('gst_periods', schema='solar')
    # ### end Alembic commands ###
