"""Update eb application stages and add eb_documents

Revision ID: a6898c7b2c05
Revises: 3f475a42e7ac
Create Date: 2026-08-23 21:29:39.341230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6898c7b2c05'
down_revision: Union[str, None] = '3f475a42e7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eb_documents',
    sa.Column('eb_application_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['eb_application_id'], ['solar.eb_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_eb_documents_eb_application_id'), 'eb_documents', ['eb_application_id'], unique=False, schema='solar')
    postgresql.ENUM('Application Received', 'Document Collection', 'Document Verification', 'EB/TANGEDCO Portal Submission', 'EB Process / Awaiting Further Action', 'Handover Application with EB Meter Supply', name='eb_app_stage_enum_v2', schema='solar').create(op.get_bind())
    op.execute('ALTER TABLE solar.eb_applications ALTER COLUMN current_stage TYPE solar.eb_app_stage_enum_v2 USING current_stage::text::solar.eb_app_stage_enum_v2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eb_applications', 'current_stage',
               existing_type=sa.Enum('Application Received', 'Document Collection', 'Document Verification', 'EB/TANGEDCO Portal Submission', 'EB Process / Awaiting Further Action', 'Handover Application with EB Meter Supply', name='eb_app_stage_enum_v2', schema='solar'),
               type_=postgresql.ENUM('Application Received', 'EB Document Verification', 'Application Submitted in Portal - Admin', 'Handover Application with EB Meter Supply', name='eb_app_stage_enum', schema='solar'),
               existing_nullable=False,
               schema='solar')
    op.drop_index(op.f('ix_solar_eb_documents_eb_application_id'), table_name='eb_documents', schema='solar')
    op.drop_table('eb_documents', schema='solar')
    # ### end Alembic commands ###
