"""Add customer_phone to quotations

Revision ID: aaf4d33be9f1
Revises: a6898c7b2c05
Create Date: 2026-08-25 10:31:08.971111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf4d33be9f1'
down_revision: Union[str, None] = 'a6898c7b2c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('customer_phone', sa.String(length=20), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'customer_phone', schema='solar')
    # ### end Alembic commands ###
