"""initial migration

Revision ID: bbb7d1f3806e
Revises: 
Create Date: 2026-08-15 11:47:05.331245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb7d1f3806e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('customer_type', sa.Enum('Residential', 'Commercial', 'Industrial', name='customer_type_enum', schema='solar'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('source_lead_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_lead_id'], ['solar.leads.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('teams_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='solar'
    )
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('joining_date', sa.String(length=20), nullable=False),
    sa.Column('department', sa.Enum('CEO', 'Marketing', 'Site Visit', 'Accounts', 'Project', 'Warehouse', 'Transport', name='department_enum', schema='solar'), nullable=False),
    sa.Column('designation', sa.Enum('CEO', 'Telecaller', 'Direct Marketing Executive', 'Site Visitor', 'Accountant', 'Project Head', 'Field Technician', 'Document Follow-up Executive', 'Stock Maintenance', 'Driver', 'Partner / Payment Receiver', name='designation_enum', schema='solar'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('employment_status', sa.Enum('Active', 'On Leave', 'Suspended', 'Relieved', name='employment_status_enum', schema='solar'), nullable=False),
    sa.Column('avatar_color', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('username'),
    schema='solar'
    )
    op.create_table('stock_items',
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('minimum_level', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('activity_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('actor_employee_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=300), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_activity_logs_actor_employee_id'), 'activity_logs', ['actor_employee_id'], unique=False, schema='solar')
    op.create_index(op.f('ix_solar_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False, schema='solar')
    op.create_table('approvals',
    sa.Column('approval_type', sa.Enum('Quotation Revision', 'Stock Purchase Flag', 'Leave Request', 'Project Hold', 'Discount Exception', name='approval_type_enum', schema='solar'), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raised_on', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='approval_status_enum', schema='solar'), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='approval_priority_enum', schema='solar'), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('leads',
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('customer_type', sa.Enum('Residential', 'Commercial', 'Industrial', name='lead_customer_type_enum', schema='solar'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lead_source', sa.Enum('Referral', 'Walk-in', 'Online Inquiry', 'Social Media', 'Advertisement', 'Cold Call', 'Exhibition', 'Partner', 'Government Scheme', 'Previous Customer', 'Other', name='lead_source_enum', schema='solar'), nullable=False),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('product_interested', sa.String(length=200), nullable=True),
    sa.Column('requirement_description', sa.Text(), nullable=True),
    sa.Column('approximate_requirement', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='lead_priority_enum', schema='solar'), nullable=False),
    sa.Column('assigned_employee_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('first_contact_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('New', 'Contacted', 'Interested', 'Follow-up', 'Site Visit Required', 'Site Visit Scheduled', 'Quotation Stage', 'Lost', 'Converted', name='lead_status_enum', schema='solar'), nullable=False),
    sa.Column('lost_reason', sa.Enum('Price Too High', 'Went with Competitor', 'Not Interested', 'Budget Issues', 'No Response', 'Project Cancelled', 'Technical Mismatch', 'Other', name='lead_lost_reason_enum', schema='solar'), nullable=True),
    sa.Column('lost_reason_detail', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('customer_origin', sa.Enum('New Lead', 'Existing Customer', name='customer_origin_enum', schema='solar'), nullable=True),
    sa.Column('prior_project_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['solar.customers.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['prior_project_id'], ['solar.projects.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('notifications',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('department', sa.Enum('CEO', 'Marketing', 'Site Visit', 'Accounts', 'Project', 'Warehouse', 'Transport', name='notification_dept_enum', schema='solar'), nullable=True),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='notification_priority_enum', schema='solar'), nullable=False),
    sa.Column('category', sa.Enum('Approval', 'Payment', 'Stock', 'Project', 'Leave', 'System', name='notification_category_enum', schema='solar'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False, schema='solar')
    op.create_table('performance_records',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('completed_work', sa.Integer(), nullable=False),
    sa.Column('pending_work', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_performance_records_employee_id'), 'performance_records', ['employee_id'], unique=False, schema='solar')
    op.create_table('projects',
    sa.Column('project_code', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_mobile', sa.String(length=20), nullable=True),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('project_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capacity_kw', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('assigned_technician_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_doc_employee_id', sa.String(length=36), nullable=True),
    sa.Column('current_stage', sa.Enum('Site Visit', 'Quotation', 'Awaiting Advance Payment', 'Advance Payment', 'Project Execution', 'Installation', 'Final Connection', 'Completed', name='project_stage_enum', schema='solar'), nullable=False),
    sa.Column('status', sa.Enum('On Track', 'Delayed', 'On Hold', 'Completed', 'Issue Raised', name='project_status_enum', schema='solar'), nullable=False),
    sa.Column('warehouse_status', sa.Enum('Not Requested', 'Requested', 'Reserved', 'Issued', name='warehouse_status_enum', schema='solar'), nullable=False),
    sa.Column('eb_status', sa.Enum('Not Started', 'Application Submitted', 'Meter Installed', 'Connected', name='eb_status_enum', schema='solar'), nullable=False),
    sa.Column('installation_status', sa.Enum('Not Started', 'In Progress', 'Completed', name='installation_status_enum', schema='solar'), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', name='project_priority_enum', schema='solar'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doc_employee_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['solar.customers.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['solar.quotations.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code'),
    schema='solar'
    )
    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(length=30), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('previous_quotation_id', sa.String(length=36), nullable=True),
    sa.Column('revision_reason', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('site', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.String(length=20), nullable=True),
    sa.Column('prepared_by', sa.String(length=200), nullable=False),
    sa.Column('prepared_by_id', sa.String(length=36), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Submitted', 'Sent', 'Customer Review', 'Revision Required', 'Customer Approved', 'Customer Rejected', 'Awaiting Advance', 'Expired', name='quotation_status_enum', schema='solar'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labour_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_charges', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('installation_terms', sa.Text(), nullable=True),
    sa.Column('warranty_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_ceo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['solar.leads.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_quotation_id'], ['solar.quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=False, schema='solar')
    op.create_table('call_log_entries',
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('called_by', sa.String(length=200), nullable=False),
    sa.Column('called_by_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.Enum('Answered', 'Not Reachable', 'Call Back Requested', 'Switched Off', 'Wrong Number', name='call_outcome_enum', schema='solar'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_follow_up_date', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['called_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['solar.leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_call_log_entries_lead_id'), 'call_log_entries', ['lead_id'], unique=False, schema='solar')
    op.create_table('field_movements',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('Checked In', 'On Field', 'Returning', 'Checked Out', name='field_movement_status_enum', schema='solar'), nullable=False),
    sa.Column('current_location', sa.String(length=500), nullable=True),
    sa.Column('destination', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['solar.leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_field_movements_employee_id'), 'field_movements', ['employee_id'], unique=False, schema='solar')
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('leave_type', sa.Enum('Casual', 'Sick', 'Emergency', 'Unpaid', name='leave_type_enum', schema='solar'), nullable=False),
    sa.Column('from_date', sa.String(length=20), nullable=False),
    sa.Column('to_date', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='leave_status_enum', schema='solar'), nullable=False),
    sa.Column('applied_on', sa.String(length=20), nullable=False),
    sa.Column('ceo_remarks', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['solar.approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False, schema='solar')
    op.create_table('payments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_type', sa.Enum('Advance (50%)', 'Balance Payment', 'Partial Payment', 'Full Payment', name='payment_type_enum', schema='solar'), nullable=False),
    sa.Column('payment_date', sa.String(length=20), nullable=True),
    sa.Column('payment_mode', sa.Enum('UPI', 'Bank Transfer', 'Cheque', 'Cash', 'Card', name='payment_mode_enum', schema='solar'), nullable=True),
    sa.Column('transaction_reference', sa.String(length=200), nullable=True),
    sa.Column('state', sa.Enum('Pending', 'Partial', 'Proof Uploaded', 'Under Verification', 'Verified', 'Rejected', name='payment_state_enum', schema='solar'), nullable=False),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('submitted_by_id', sa.String(length=36), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['solar.quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_payments_project_id'), 'payments', ['project_id'], unique=False, schema='solar')
    op.create_table('project_stage_histories',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_project_stage_histories_project_id'), 'project_stage_histories', ['project_id'], unique=False, schema='solar')
    op.create_table('quotation_line_items',
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('labour_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['solar.quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_quotation_line_items_quotation_id'), 'quotation_line_items', ['quotation_id'], unique=False, schema='solar')
    op.create_table('stock_reservations',
    sa.Column('stock_item_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.Enum('Requested', 'Reserved', 'Issued', 'Returned', 'Cancelled', 'Shortage Flagged', name='stock_reservation_status_enum', schema='solar'), nullable=False),
    sa.Column('reserved_by_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['solar.stock_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_stock_reservations_project_id'), 'stock_reservations', ['project_id'], unique=False, schema='solar')
    op.create_index(op.f('ix_solar_stock_reservations_stock_item_id'), 'stock_reservations', ['stock_item_id'], unique=False, schema='solar')
    op.create_table('stock_transactions',
    sa.Column('stock_item_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.Enum('Stock In', 'Stock Out', 'Issue', 'Return', 'Adjustment', name='stock_transaction_type_enum', schema='solar'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['solar.stock_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_stock_transactions_stock_item_id'), 'stock_transactions', ['stock_item_id'], unique=False, schema='solar')
    op.create_table('field_movement_notes',
    sa.Column('field_movement_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_movement_id'], ['solar.field_movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_field_movement_notes_field_movement_id'), 'field_movement_notes', ['field_movement_id'], unique=False, schema='solar')
    op.create_table('field_movement_photos',
    sa.Column('field_movement_id', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['field_movement_id'], ['solar.field_movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_field_movement_photos_field_movement_id'), 'field_movement_photos', ['field_movement_id'], unique=False, schema='solar')
    op.create_table('field_movement_route_points',
    sa.Column('field_movement_id', sa.String(length=36), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['field_movement_id'], ['solar.field_movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_field_movement_route_points_field_movement_id'), 'field_movement_route_points', ['field_movement_id'], unique=False, schema='solar')
    op.create_table('payment_proofs',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['solar.payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_payment_proofs_payment_id'), 'payment_proofs', ['payment_id'], unique=False, schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_payment_proofs_payment_id'), table_name='payment_proofs', schema='solar')
    op.drop_table('payment_proofs', schema='solar')
    op.drop_index(op.f('ix_solar_field_movement_route_points_field_movement_id'), table_name='field_movement_route_points', schema='solar')
    op.drop_table('field_movement_route_points', schema='solar')
    op.drop_index(op.f('ix_solar_field_movement_photos_field_movement_id'), table_name='field_movement_photos', schema='solar')
    op.drop_table('field_movement_photos', schema='solar')
    op.drop_index(op.f('ix_solar_field_movement_notes_field_movement_id'), table_name='field_movement_notes', schema='solar')
    op.drop_table('field_movement_notes', schema='solar')
    op.drop_index(op.f('ix_solar_stock_transactions_stock_item_id'), table_name='stock_transactions', schema='solar')
    op.drop_table('stock_transactions', schema='solar')
    op.drop_index(op.f('ix_solar_stock_reservations_stock_item_id'), table_name='stock_reservations', schema='solar')
    op.drop_index(op.f('ix_solar_stock_reservations_project_id'), table_name='stock_reservations', schema='solar')
    op.drop_table('stock_reservations', schema='solar')
    op.drop_index(op.f('ix_solar_quotation_line_items_quotation_id'), table_name='quotation_line_items', schema='solar')
    op.drop_table('quotation_line_items', schema='solar')
    op.drop_index(op.f('ix_solar_project_stage_histories_project_id'), table_name='project_stage_histories', schema='solar')
    op.drop_table('project_stage_histories', schema='solar')
    op.drop_index(op.f('ix_solar_payments_project_id'), table_name='payments', schema='solar')
    op.drop_table('payments', schema='solar')
    op.drop_index(op.f('ix_solar_leave_requests_employee_id'), table_name='leave_requests', schema='solar')
    op.drop_table('leave_requests', schema='solar')
    op.drop_index(op.f('ix_solar_field_movements_employee_id'), table_name='field_movements', schema='solar')
    op.drop_table('field_movements', schema='solar')
    op.drop_index(op.f('ix_solar_call_log_entries_lead_id'), table_name='call_log_entries', schema='solar')
    op.drop_table('call_log_entries', schema='solar')
    op.drop_index(op.f('ix_solar_quotations_quotation_number'), table_name='quotations', schema='solar')
    op.drop_table('quotations', schema='solar')
    op.drop_table('projects', schema='solar')
    op.drop_index(op.f('ix_solar_performance_records_employee_id'), table_name='performance_records', schema='solar')
    op.drop_table('performance_records', schema='solar')
    op.drop_index(op.f('ix_solar_notifications_recipient_id'), table_name='notifications', schema='solar')
    op.drop_table('notifications', schema='solar')
    op.drop_table('leads', schema='solar')
    op.drop_table('approvals', schema='solar')
    op.drop_index(op.f('ix_solar_activity_logs_timestamp'), table_name='activity_logs', schema='solar')
    op.drop_index(op.f('ix_solar_activity_logs_actor_employee_id'), table_name='activity_logs', schema='solar')
    op.drop_table('activity_logs', schema='solar')
    op.drop_table('stock_items', schema='solar')
    op.drop_table('employees', schema='solar')
    op.drop_table('departments', schema='solar')
    op.drop_table('customers', schema='solar')
    # ### end Alembic commands ###
