"""Add ProjectAssignment and ProjectUpload models

Revision ID: c2db0c122054
Revises: 59bc01e3f57a
Create Date: 2026-08-29 11:31:04.949673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2db0c122054'
down_revision: Union[str, None] = '59bc01e3f57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Products table created elsewhere
    op.create_table('project_assignments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('Technician', 'Follow-Up', name='project_assignment_role_enum', schema='solar'), nullable=False),
    sa.Column('assignment_type', sa.Enum('Primary', 'Additional', name='project_assignment_type_enum', schema='solar'), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['solar.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('project_uploads',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['solar.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_uploads', schema='solar')
    op.drop_table('project_assignments', schema='solar')
    op.drop_index(op.f('ix_solar_products_name'), table_name='products', schema='solar')
    op.drop_table('products', schema='solar')
    # ### end Alembic commands ###
