"""add solar columns to quotations

Revision ID: c49c8aba9923
Revises: 23023eb82e8d
Create Date: 2026-08-28 12:08:52.033860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49c8aba9923'
down_revision: Union[str, None] = '23023eb82e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('solar_panel', sa.String(length=300), nullable=True), schema='solar')
    op.add_column('quotations', sa.Column('solar_inverter', sa.String(length=300), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'solar_inverter', schema='solar')
    op.drop_column('quotations', 'solar_panel', schema='solar')
    # ### end Alembic commands ###
