"""Add site visits models

Revision ID: cedf2d7f415a
Revises: bbb7d1f3806e
Create Date: 2026-08-17 22:43:52.724537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedf2d7f415a'
down_revision: Union[str, None] = 'bbb7d1f3806e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visits',
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_mobile', sa.String(length=20), nullable=False),
    sa.Column('site_address', sa.String(length=500), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('customer_latitude', sa.Float(), nullable=True),
    sa.Column('customer_longitude', sa.Float(), nullable=True),
    sa.Column('visit_date', sa.String(length=20), nullable=False),
    sa.Column('visit_time', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('site_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('Upcoming', 'In Progress', 'Completed', 'Revisit Required', 'Rejected', name='site_visit_status_enum', schema='solar'), nullable=False),
    sa.Column('feasibility_result', sa.String(length=200), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('rejection_remarks', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['solar.leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('site_visit_locations',
    sa.Column('site_visit_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('distance_from_customer', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_visit_id'], ['solar.site_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_table('site_visit_photos',
    sa.Column('site_visit_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('distance_from_customer', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_visit_id'], ['solar.site_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='solar'
    )
    op.create_foreign_key(None, 'customers', 'leads', ['source_lead_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'leads', 'customers', ['customer_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'leads', 'projects', ['prior_project_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'projects', 'customers', ['customer_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'projects', 'quotations', ['quotation_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'quotations', 'leads', ['lead_id'], ['id'], source_schema='solar', referent_schema='solar', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', schema='solar', type_='foreignkey')
    op.drop_constraint(None, 'projects', schema='solar', type_='foreignkey')
    op.drop_constraint(None, 'projects', schema='solar', type_='foreignkey')
    op.drop_constraint(None, 'leads', schema='solar', type_='foreignkey')
    op.drop_constraint(None, 'leads', schema='solar', type_='foreignkey')
    op.drop_constraint(None, 'customers', schema='solar', type_='foreignkey')
    op.drop_table('site_visit_photos', schema='solar')
    op.drop_table('site_visit_locations', schema='solar')
    op.drop_table('site_visits', schema='solar')
    # ### end Alembic commands ###
