"""Add payment_type and pending ceo assignment status to lead

Revision ID: dfc7414c4e4c
Revises: c2db0c122054
Create Date: 2026-08-29 12:12:17.499579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc7414c4e4c'
down_revision: Union[str, None] = 'c2db0c122054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE solar.lead_status_enum ADD VALUE IF NOT EXISTS 'Pending CEO Assignment';")
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_payment_type_enum') THEN
                CREATE TYPE solar.lead_payment_type_enum AS ENUM ('Loan', 'Own Payment');
            END IF;
        END
        $$;
    """)
    op.add_column('leads', sa.Column('payment_type', sa.Enum('Loan', 'Own Payment', name='lead_payment_type_enum', schema='solar', create_type=False), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'payment_type', schema='solar')
    op.execute("DROP TYPE solar.lead_payment_type_enum;")
    # ### end Alembic commands ###
