"""Add employee fields

Revision ID: e4a7b625a602
Revises: aaf4d33be9f1
Create Date: 2026-08-25 11:28:15.892005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a7b625a602'
down_revision: Union[str, None] = 'aaf4d33be9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('family_number', sa.String(length=20), nullable=True), schema='solar')
    op.add_column('employees', sa.Column('office_number', sa.String(length=20), nullable=True), schema='solar')
    op.add_column('employees', sa.Column('document_1', sa.String(length=200), nullable=True), schema='solar')
    op.add_column('employees', sa.Column('document_2', sa.String(length=200), nullable=True), schema='solar')
    op.add_column('employees', sa.Column('document_3', sa.String(length=200), nullable=True), schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'document_3', schema='solar')
    op.drop_column('employees', 'document_2', schema='solar')
    op.drop_column('employees', 'document_1', schema='solar')
    op.drop_column('employees', 'office_number', schema='solar')
    op.drop_column('employees', 'family_number', schema='solar')
    # ### end Alembic commands ###
