"""Add employee_financials table

Revision ID: f6e461f7144e
Revises: 59bc01e3f57a
Create Date: 2026-08-29 11:50:14.851879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e461f7144e'
down_revision: Union[str, None] = '59bc01e3f57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('employee_financials',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['solar.employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_employee_financial'),
    schema='solar'
    )
    op.create_index(op.f('ix_solar_employee_financials_employee_id'), 'employee_financials', ['employee_id'], unique=True, schema='solar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_employee_financials_employee_id'), table_name='employee_financials', schema='solar')
    op.drop_table('employee_financials', schema='solar')

    # ### end Alembic commands ###
